### ISSUE TITLE
Implement User Premium Status Update on Tebex Payment Completion

### ISSUE THREAD

**Issue by cheesea3** [imperfectandcompany/Imperfect-Host-Webhook#8]
Enhance the webhook handling service to update the user's premium status in our PHP REST API when a payment is completed through Tebex. This involves making a PUT request to the specified API endpoint with the necessary user information extracted from the Tebex payment completion payload.

## Details:

**PHP REST API Routes:**
- **Update Premium Status:**
  - **Endpoint:** `https://api.imperfectgamers.org/premium/update/user/:id/:premium_status`
  - **Method:** `PUT`
  - **Parameters:** 
    - **Path:**
      - `id` (user ID)
      - `premium_status` (true/false)
    - **Body:**
      - `steam_id`
      - `username`
      - `email`

- **Check Premium Status:**
  - **Endpoint:** `https://api.imperfectgamers.org/premium/status/:user_id`
  - **Method:** `GET`

**Tebex Payment Completion Payload:**
```json
{
  "id": 1,
  "description": "Complete",
  "payment_sequence": "first",
  "created_at": "2024-06-07T01:44:25.000Z",
  "price": {
    "amount": 10,
    "currency": "USD"
  },
  "customer": {
    "first_name": "John",
    "last_name": "Cena",
    "email": "JohnCena@gmail.com"
  },
  "cart": {
    "id": "##82819#",
    "products": [
      {
        "custom": {
          "user_id": #8#,
          "username": "JohnCena",
          "steam_id": "7656119##5919##00"
        }
      }
    ]
  }
}
```

**Steps:**

1. **Extract User Information:**
   - Extract `user_id`, `username`, and `steam_id` from the `custom` object in the payload.
   - Extract `email` from the `customer` object in the payload.

2. **Construct API Request:**
   - Construct a PUT request to `https://api.imperfectgamers.org/premium/update/user/:id/:premium_status` with the path parameters `id` and `premium_status`.
   - Include the following in the request body:
     ```json
     {
       "steam_id": "7656119##5919##00",
       "username": "JohnCena",
       "email": "JohnCena@gmail.com"
     }
     ```

3. **Handle API Response:**
   - Expect a JSON response with a status message.
   - Ensure the response status code is 200 for successful updates.

**Expected API Response:**
```json
{
  "status": "success",
  "message": "Premium status updated successfully"
}
```

**Tasks:**
- [ ] Modify the `handlePaymentCompleted` function in `webhooks/services/paymentServices.js` to include the logic for making the PUT request.
- [ ] Use a suitable HTTP client library (e.g., `axios`) to make the PUT request to the PHP REST API.
- [ ] Handle different scenarios such as successful updates, errors, and invalid responses.
- [ ] Update the documentation and add any necessary comments for clarity.

**Example Implementation:**

1. **Install Axios:**
   ```bash
   npm install axios
   ```

2. **Update handlePaymentCompleted:**
   ```javascript
   const axios = require('axios');

   async function handlePaymentCompleted(event, res) {
     logWithTraceId(event.id, `Payment completed: ${JSON.stringify(event.subject)}`);
     const userId = event.cart.products[0].custom.user_id;
     const steamId = event.cart.products[0].custom.steam_id;
     const username = event.cart.products[0].custom.username;
     const email = event.customer.email;
     const url = `https://api.imperfectgamers.org/premium/update/user/${userId}/true`;

     try {
       const response = await axios.put(url, {
         steam_id: steamId,
         username: username,
         email: email
       });

       if (response.status === 200 && response.data.status === 'success') {
         logWithTraceId(event.id, 'Premium status updated successfully');
         res.status(200).send('Premium status updated successfully');
       } else {
         throw new Error('Failed to update premium status');
       }
     } catch (error) {
       console.error('Error updating premium status:', error);
       res.status(500).send('Error updating premium status');
     }
   }
   ```

**Additional Notes:**
- Ensure error handling covers all potential failure points.
- Test the integration thoroughly with different scenarios to ensure reliability.
